import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>NT Static Form</title>
        <meta name="description" content="Generated by Nhat Tien" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <div className="flex w-full flex-col items-start justify-center bg-slate-950 px-96 py-5">
          <h1 className="text-muted">Start a new Form</h1>
          <div className="flex items-center justify-center">
            <div className="flex flex-col items-start justify-center">
              <Link href={"/form"}>
                <Image
                  src={"/forms-blank-googlecolors.png"}
                  alt="add new form"
                  width={192}
                  height={192}
                  className="my-3 rounded border border-gray-300 hover:cursor-pointer hover:border-slate-900"
                />
              </Link>
              <h1 className="text-muted">New form</h1>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}

// function AuthShowcase() {
//   const { data: sessionData } = useSession();

//   const { data: secretMessage } = api.post.getSecretMessage.useQuery(
//     undefined, // no input
//     { enabled: sessionData?.user !== undefined }
//   );

//   return (
//     <div className="flex flex-col items-center justify-center gap-4">
//       <p className="text-center text-2xl text-white">
//         {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
//         {secretMessage && <span> - {secretMessage}</span>}
//       </p>
//       <button
//         className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
//         onClick={sessionData ? () => void signOut() : () => void signIn()}
//       >
//         {sessionData ? "Sign out" : "Sign in"}
//       </button>
//     </div>
//   );
// }
