import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useSession, signIn, signOut } from "next-auth/react";

export default function Home() {
  return (
    <>
      <Head>
        <title>NT Static Form</title>
        <meta name="description" content="Generated by Nhat Tien" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <div className="flex w-full flex-col items-start justify-center bg-slate-950 px-96 py-5">
          <h1 className="text-muted">Start a new Form</h1>
          <div className="flex items-center justify-center">
            <div className="flex flex-col items-start justify-center">
              <Link href={"/form"}>
                <Image
                  src={"/forms-blank-googlecolors.png"}
                  alt="add new form"
                  width={192}
                  height={192}
                  className="my-3 rounded border border-gray-300 hover:cursor-pointer hover:border-slate-900"
                />
              </Link>
              <h1 className="text-muted">New form</h1>
            </div>
          </div>
        </div>
        <AuthShowcase />
      </main>
    </>
  );
}

function AuthShowcase() {
  const { data: sessionData, status } = useSession();

  console.log("sessionData: ", { sessionData });
  console.log("status: ", { status });

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <button
        className=""
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
}
